articleEvenement/src/main/java/com/example/articleevenement/model/Post.java
package com.example.articleevenement.model;

import com.example.articleevenement.model.common.BaseModel;
import lombok.Getter;
import lombok.Setter;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.web.multipart.MultipartFile;

import javax.persistence.*;
import java.util.Date;

import static com.example.articleevenement.util.DateUtil.formatDate;
import static com.example.articleevenement.util.DateUtil.getDateNow;
import static com.example.articleevenement.util.ImageUtil.getBase64Image;

@Entity
@Getter
@Setter
public class Post extends BaseModel {
    private String title;
    private String description;

    @Temporal(TemporalType.TIMESTAMP)
    @DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm")
    private Date date1;

    @Temporal(TemporalType.TIMESTAMP)
    @DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm")
    private Date date2;

    @ManyToOne
    private Type type;

    private String location;

    private Integer status;

    @ManyToOne
    private Author author;

    @Column(columnDefinition = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP", insertable = false)
    @Temporal(TemporalType.TIMESTAMP)
    @DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm")
    private Date creation_date;

    @Temporal(TemporalType.TIMESTAMP)
    @DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm")
    private Date pub_date;

    private Integer is_priority;

    @Transient
    private Integer type_id;

    private String image;

    @Transient
    private MultipartFile imageFile;

    public void setImage() throws Exception {
        if (getImageFile() != null && !getImageFile().isEmpty()) {
            try {
                image = getBase64Image(imageFile);
            } catch (Exception e) {
                throw e;
            }
        }
    }

    public void setDate1(Date date) throws Exception {
        if (getDate2() != null) {
            if (date.after(getDate2())) {
                this.date1 = date;
                throw new Exception("La date 1 doit etre anterieur a la date 2");
            }
        }
        this.date1 = date;
    }

    public void setDate2(Date date) throws Exception {
        if (getDate1() != null) {
            if (date.before(getDate1())) {
                this.date2 = date;
                throw new Exception("La date 2 doit etre posterieur a la date 1");
            }
        }
        this.date2 = date;
    }

    public void setPub_date(Date date) throws Exception {
        if (getPub_date() != null && date.compareTo(getPub_date()) == 0) {
            this.pub_date = date;
        }
        else if (date != null && date.before(getDateNow())) {
            this.pub_date = date;
            throw new Exception("La date de publication doit etre posterieur a aujourd'hui");
        }
        this.pub_date = date;

    }

    public String getDate1ToString() {
        return formatDate(getDate1());
    }

    public String getDate2ToString() {
        return formatDate(getDate2());
    }

    public String getDateCreationToString() {
        return formatDate(getCreation_date());
    }

    public String getDatePubToString() {
        return formatDate(getPub_date());
    }

    public String getTitleToUpperCase() {
        return getTitle().toUpperCase();
    }

    public Boolean isArticle() {
        if (getType() != null && getType().getId() == 1) {
            return true;
        }
        return false;
    }
}

articleEvenement/src/main/java/com/example/articleevenement/controller/PostController.java
package com.example.articleevenement.controller;

import com.example.articleevenement.model.Author;
import com.example.articleevenement.model.Post;
import com.example.articleevenement.model.Type;
import com.example.articleevenement.service.PostService;
import com.example.articleevenement.service.TypeService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.stereotype.Controller;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.ModelAndView;

import javax.servlet.http.HttpSession;
import java.util.Date;

import static com.example.articleevenement.util.ControllerUtil.getMessage;

@Controller
@RequestMapping("/post")
public class PostController {

    @Autowired
    private PostService postService;

    @Autowired
    private TypeService typeService;

    @Autowired
    private HttpSession session;

    @GetMapping("/new")
    public ModelAndView loadPostForm(@RequestParam(required = false) String error) throws Exception {
        if (session.getAttribute("author") == null) {
            return new ModelAndView("redirect:/author/login");
        }
        ModelAndView modelAndView = new ModelAndView();
        modelAndView.addObject("command", new Post());
        modelAndView.addObject("types", typeService.findAll(new Type(), null));
        modelAndView.addObject("error", error);
        modelAndView.addObject("side", "author");
        modelAndView.addObject("event", "save");
        modelAndView.addObject("action", "post");
        modelAndView.setViewName("postForm");
        return modelAndView;
    }

    @GetMapping("{id}/update")
    public ModelAndView loadUpdateForm(@PathVariable Integer id, @RequestParam(required = false) String error) throws Exception {

        ModelAndView modelAndView = new ModelAndView();
        modelAndView.addObject("command", postService.findById(Post.class, id));
        modelAndView.addObject("error", error);
        if (session.getAttribute("admin") != null) {
            modelAndView.addObject("side", "admin");
        } else {
            modelAndView.addObject("side", "author");
        }

        modelAndView.addObject("types", typeService.findAll(new Type(), null));
        modelAndView.addObject("event", "update");
        modelAndView.addObject("action", "post/" + id );
        modelAndView.setViewName("postForm");
        return modelAndView;
    }

    @PostMapping
    public ModelAndView savePost(@ModelAttribute Post post, BindingResult bindingResult) throws Exception {
        ModelAndView modelAndView = new ModelAndView();
        if (bindingResult.hasErrors()) {
            String message = getMessage(bindingResult);
            modelAndView.setViewName("redirect:/post/new?error=" + message);
            return modelAndView;
        }
        try {
            Author author = (Author) session.getAttribute("author");
            post.setAuthor(author);
            postService.save(post);
            modelAndView.setViewName("redirect:/post/author");
        } catch (Exception e) {
            e.printStackTrace();
            modelAndView.setViewName("redirect:/post/new?error=" + e.getMessage());
        }
        return modelAndView;
    }

    @PostMapping("{id}")
    public ModelAndView updatePost(@PathVariable Integer id, @ModelAttribute Post post, BindingResult bindingResult) throws Exception {
        ModelAndView modelAndView = new ModelAndView();

        if (bindingResult.hasErrors()) {

        }

        try {
            post.setId(id);
            postService.update(post);
            if (session.getAttribute("author") != null) {
                modelAndView.setViewName("redirect:/post/author");
            } else if (session.getAttribute("admin") != null) {
                modelAndView.setViewName("redirect:/post/admin");
            }
        } catch (Exception e) {
            modelAndView.setViewName("redirect:/post/" + id + "/update?error=" + e.getMessage());

        }
        return modelAndView;
    }

    @GetMapping("/admin")
    public ModelAndView loadPostsForBack(@RequestParam(required = false) Integer page, @RequestParam(required = false) String search, @RequestParam(required = false) Integer status, @RequestParam(required = false) String error) throws Exception {
        if (session.getAttribute("admin") == null) {
            return new ModelAndView("redirect:/admin/login");
        }
        ModelAndView modelAndView = new ModelAndView();
        Post post = new Post();
        if (status != null && status != 2) {
            post.setStatus(status);
        }
        getListModelAndView(page, search, modelAndView, post, error, false);
        if (status != null) {
            modelAndView.addObject("status", status);
        }
        modelAndView.addObject("side", "admin");
        modelAndView.setViewName("postList");
        return modelAndView;
    }


    @GetMapping("/front")
    public ModelAndView loadPostsForFront(@RequestParam(required = false) Integer page, @RequestParam(required = false) String search, @RequestParam(required = false) String error) throws Exception {
//        if (session.getAttribute("author") == null) {
//            return new ModelAndView("redirect:/author/login");
//        }
        ModelAndView modelAndView = new ModelAndView();
        Post post = new Post();
        post.setStatus(1);
        getListModelAndView(page, search, modelAndView, post, error, true);
        modelAndView.addObject("side", "front");
        modelAndView.setViewName("postList");
        return modelAndView;
    }

    @GetMapping("/author")
    public ModelAndView loadAuthorsPosts(@RequestParam(required = false) Integer page, @RequestParam(required = false) String search, @RequestParam(required = false) Integer status, @RequestParam(required = false) String error) throws Exception {
        if (session.getAttribute("author") == null) {
            return new ModelAndView("redirect:/author/login");
        }
        ModelAndView modelAndView = new ModelAndView();
        Post post = new Post();
        if (status != null && status != 2) {
            post.setStatus(status);
        }
        post.setAuthor((Author) session.getAttribute("author"));
        getListModelAndView(page, search, modelAndView, post, error, false);
        if (status != null) {
            modelAndView.addObject("status", status);
        }
        modelAndView.addObject("side", "author");
        modelAndView.setViewName("postList");
        return modelAndView;
    }

    private void getListModelAndView(Integer page, String search, ModelAndView modelAndView, Post post, String error, Boolean isAuthor) throws Exception {
        modelAndView.addObject("posts", postService.findAllWithResearchAndPagination(post, search, page, isAuthor));
        if (search != null) {
            modelAndView.addObject("search", search);
        }
        modelAndView.addObject("error", error);
        modelAndView.addObject("pageCount", postService.getPagesCount(post, search, isAuthor));
        if (page != null) {
            modelAndView.addObject("page", page);
        } else {
            modelAndView.addObject("page", 1);
        }
    }

    @PostMapping("{id}/validate")
    public ModelAndView validate(@PathVariable Integer id, @RequestParam @DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm") Date pubDate) throws Exception {
        System.out.println("id is " + id);
        ModelAndView modelAndView = new ModelAndView();
        try {
            postService.updatePostState(id, pubDate);
            modelAndView.setViewName("redirect:/post/admin");
        } catch (Exception e) {
            modelAndView.setViewName("redirect:/post/admin?error=" + e.getMessage());
        }

        return modelAndView;
    }

}

articleEvenement/src/main/webapp/WEB-INF/views/footer_admin.jsp
<!-- Start Footer -->
<footer class="bg-dark" id="tempaltemo_footer">
    <div class="container">
        <div class="row">

            <div class="col-md-4 pt-5">
                <h2 class="h2 text-success border-bottom pb-3 border-light logo">Zay</h2>
                <ul class="list-unstyled text-light footer-link-list">
                    <li>
                        <i class="fas fa-map-marker-alt fa-fw"></i>
                        Andoharanofotsy, Antananarivo, Madagascar
                    </li>
                    <li>
                        <i class="fa fa-phone fa-fw"></i>
                        <a class="text-decoration-none" href="tel:010-020-0340">010-020-0340</a>
                    </li>
                    <li>
                        <i class="fa fa-envelope fa-fw"></i>
                        <a class="text-decoration-none" href="mailto:info@company.com">info@zay.com</a>
                    </li>
                </ul>
            </div>

            <div class="col-md-4 pt-5">

            </div>

            <div class="col-md-4 pt-5">
                <h2 class="h2 text-light border-bottom pb-3 border-light">Further Info</h2>
                <ul class="list-unstyled text-light footer-link-list">
                    <li><a class="text-decoration-none" href="${pageContext.request.contextPath}/post/admin">Posts</a></li>
                    <li><a class="text-decoration-none" href="#">About Us</a></li>
                    <li><a class="text-decoration-none" href="#">Contact</a></li>
                </ul>
            </div>

        </div>

        <div class="row text-light mb-4">
            <div class="col-12 mb-3">
                <div class="w-100 my-3 border-top border-light"></div>
            </div>
            <div class="col-auto me-auto">
                <ul class="list-inline text-left footer-icons">
                    <li class="list-inline-item border border-light rounded-circle text-center">
                        <a class="text-light text-decoration-none" target="_blank" href="http://facebook.com/"><i class="fab fa-facebook-f fa-lg fa-fw"></i></a>
                    </li>
                    <li class="list-inline-item border border-light rounded-circle text-center">
                        <a class="text-light text-decoration-none" target="_blank" href="https://www.instagram.com/"><i class="fab fa-instagram fa-lg fa-fw"></i></a>
                    </li>
                    <li class="list-inline-item border border-light rounded-circle text-center">
                        <a class="text-light text-decoration-none" target="_blank" href="https://twitter.com/"><i class="fab fa-twitter fa-lg fa-fw"></i></a>
                    </li>
                    <li class="list-inline-item border border-light rounded-circle text-center">
                        <a class="text-light text-decoration-none" target="_blank" href="https://www.linkedin.com/"><i class="fab fa-linkedin fa-lg fa-fw"></i></a>
                    </li>
                </ul>
            </div>
            <div class="col-auto">
                <label class="sr-only" for="subscribeEmail">Email address</label>
                <div class="input-group mb-2">
                    <input type="text" class="form-control bg-dark border-light" id="subscribeEmail" placeholder="Email address">
                    <div class="input-group-text btn-success text-light">Subscribe</div>
                </div>
            </div>
        </div>
    </div>

    <div class="w-100 bg-black py-3">
        <div class="container">
            <div class="row pt-2">
                <div class="col-12">
                    <p class="text-left text-light">
                        Copyright &copy; 2023 Zay. All rights reserved.
                        | Designed by <a rel="sponsored" href="https://templatemo.com" target="_blank">TemplateMo</a>
                    </p>
                </div>
            </div>
        </div>
    </div>

</footer>
<!-- End Footer -->

<!-- Start Script -->
<script src="${pageContext.request.contextPath}/resources/assets/js/jquery-1.11.0.min.js"></script>
<script src="${pageContext.request.contextPath}/resources/assets/js/jquery-migrate-1.2.1.min.js"></script>
<script src="${pageContext.request.contextPath}/resources/assets/js/bootstrap.bundle.min.js"></script>
<script src="${pageContext.request.contextPath}/resources/assets/js/templatemo.js"></script>
<script src="${pageContext.request.contextPath}/resources/assets/js/custom.js"></script>
<!-- End Script -->
</body>

articleEvenement/src/main/webapp/WEB-INF/views/footer_author.jsp
<!-- Start Footer -->
<footer class="bg-dark" id="tempaltemo_footer">
  <div class="container">
    <div class="row">

      <div class="col-md-4 pt-5">
        <h2 class="h2 text-success border-bottom pb-3 border-light logo">Zay</h2>
        <ul class="list-unstyled text-light footer-link-list">
          <li>
            <i class="fas fa-map-marker-alt fa-fw"></i>
            Andoharanofotsy, Antananarivo, Madagascar
          </li>
          <li>
            <i class="fa fa-phone fa-fw"></i>
            <a class="text-decoration-none" href="tel:010-020-0340">010-020-0340</a>
          </li>
          <li>
            <i class="fa fa-envelope fa-fw"></i>
            <a class="text-decoration-none" href="mailto:info@company.com">info@zay.com</a>
          </li>
        </ul>
      </div>

      <div class="col-md-4 pt-5">

      </div>

      <div class="col-md-4 pt-5">
        <h2 class="h2 text-light border-bottom pb-3 border-light">Further Info</h2>
        <ul class="list-unstyled text-light footer-link-list">
          <li><a class="text-decoration-none" href="${pageContext.request.contextPath}/post/author">Posts</a></li>
          <li><a class="text-decoration-none" href="#">About Us</a></li>
          <li><a class="text-decoration-none" href="#">Contact</a></li>
        </ul>
      </div>

    </div>

    <div class="row text-light mb-4">
      <div class="col-12 mb-3">
        <div class="w-100 my-3 border-top border-light"></div>
      </div>
      <div class="col-auto me-auto">
        <ul class="list-inline text-left footer-icons">
          <li class="list-inline-item border border-light rounded-circle text-center">
            <a class="text-light text-decoration-none" target="_blank" href="http://facebook.com/"><i class="fab fa-facebook-f fa-lg fa-fw"></i></a>
          </li>
          <li class="list-inline-item border border-light rounded-circle text-center">
            <a class="text-light text-decoration-none" target="_blank" href="https://www.instagram.com/"><i class="fab fa-instagram fa-lg fa-fw"></i></a>
          </li>
          <li class="list-inline-item border border-light rounded-circle text-center">
            <a class="text-light text-decoration-none" target="_blank" href="https://twitter.com/"><i class="fab fa-twitter fa-lg fa-fw"></i></a>
          </li>
          <li class="list-inline-item border border-light rounded-circle text-center">
            <a class="text-light text-decoration-none" target="_blank" href="https://www.linkedin.com/"><i class="fab fa-linkedin fa-lg fa-fw"></i></a>
          </li>
        </ul>
      </div>
      <div class="col-auto">
        <label class="sr-only" for="subscribeEmail">Email address</label>
        <div class="input-group mb-2">
          <input type="text" class="form-control bg-dark border-light" id="subscribeEmail" placeholder="Email address">
          <div class="input-group-text btn-success text-light">Subscribe</div>
        </div>
      </div>
    </div>
  </div>

  <div class="w-100 bg-black py-3">
    <div class="container">
      <div class="row pt-2">
        <div class="col-12">
          <p class="text-left text-light">
            Copyright &copy; 2023 Zay. All rights reserved.
            | Designed by <a rel="sponsored" href="https://templatemo.com" target="_blank">TemplateMo</a>
          </p>
        </div>
      </div>
    </div>
  </div>

</footer>
<!-- End Footer -->

<!-- Start Script -->
<script src="${pageContext.request.contextPath}/resources/assets/js/jquery-1.11.0.min.js"></script>
<script src="${pageContext.request.contextPath}/resources/assets/js/jquery-migrate-1.2.1.min.js"></script>
<script src="${pageContext.request.contextPath}/resources/assets/js/bootstrap.bundle.min.js"></script>
<script src="${pageContext.request.contextPath}/resources/assets/js/templatemo.js"></script>
<script src="${pageContext.request.contextPath}/resources/assets/js/custom.js"></script>
<!-- End Script -->
</body>

articleEvenement/src/main/webapp/WEB-INF/views/footer_front.jsp
<!-- Start Footer -->
<footer class="bg-dark" id="tempaltemo_footer">
    <div class="container">
        <div class="row">

            <div class="col-md-4 pt-5">
                <h2 class="h2 text-success border-bottom pb-3 border-light logo">Zay</h2>
                <ul class="list-unstyled text-light footer-link-list">
                    <li>
                        <i class="fas fa-map-marker-alt fa-fw"></i>
                        Andoharanofotsy, Antananarivo, Madagascar
                    </li>
                    <li>
                        <i class="fa fa-phone fa-fw"></i>
                        <a class="text-decoration-none" href="tel:010-020-0340">010-020-0340</a>
                    </li>
                    <li>
                        <i class="fa fa-envelope fa-fw"></i>
                        <a class="text-decoration-none" href="mailto:info@company.com">info@zay.com</a>
                    </li>
                </ul>
            </div>

            <div class="col-md-4 pt-5">

            </div>

            <div class="col-md-4 pt-5">
                <h2 class="h2 text-light border-bottom pb-3 border-light">Further Info</h2>
                <ul class="list-unstyled text-light footer-link-list">
                    <li><a class="text-decoration-none" href="${pageContext.request.contextPath}/post/front">Posts</a></li>
                    <li><a class="text-decoration-none" href="#">About Us</a></li>
                    <li><a class="text-decoration-none" href="#">Contact</a></li>
                </ul>
            </div>

        </div>

        <div class="row text-light mb-4">
            <div class="col-12 mb-3">
                <div class="w-100 my-3 border-top border-light"></div>
            </div>
            <div class="col-auto me-auto">
                <ul class="list-inline text-left footer-icons">
                    <li class="list-inline-item border border-light rounded-circle text-center">
                        <a class="text-light text-decoration-none" target="_blank" href="http://facebook.com/"><i class="fab fa-facebook-f fa-lg fa-fw"></i></a>
                    </li>
                    <li class="list-inline-item border border-light rounded-circle text-center">
                        <a class="text-light text-decoration-none" target="_blank" href="https://www.instagram.com/"><i class="fab fa-instagram fa-lg fa-fw"></i></a>
                    </li>
                    <li class="list-inline-item border border-light rounded-circle text-center">
                        <a class="text-light text-decoration-none" target="_blank" href="https://twitter.com/"><i class="fab fa-twitter fa-lg fa-fw"></i></a>
                    </li>
                    <li class="list-inline-item border border-light rounded-circle text-center">
                        <a class="text-light text-decoration-none" target="_blank" href="https://www.linkedin.com/"><i class="fab fa-linkedin fa-lg fa-fw"></i></a>
                    </li>
                </ul>
            </div>
            <div class="col-auto">
                <label class="sr-only" for="subscribeEmail">Email address</label>
                <div class="input-group mb-2">
                    <input type="text" class="form-control bg-dark border-light" id="subscribeEmail" placeholder="Email address">
                    <div class="input-group-text btn-success text-light">Subscribe</div>
                </div>
            </div>
        </div>
    </div>

    <div class="w-100 bg-black py-3">
        <div class="container">
            <div class="row pt-2">
                <div class="col-12">
                    <p class="text-left text-light">
                        Copyright &copy; 2023 Zay. All rights reserved.
                        | Designed by <a rel="sponsored" href="https://templatemo.com" target="_blank">TemplateMo</a>
                    </p>
                </div>
            </div>
        </div>
    </div>

</footer>
<!-- End Footer -->

<!-- Start Script -->
<script src="${pageContext.request.contextPath}/resources/assets/js/jquery-1.11.0.min.js"></script>
<script src="${pageContext.request.contextPath}/resources/assets/js/jquery-migrate-1.2.1.min.js"></script>
<script src="${pageContext.request.contextPath}/resources/assets/js/bootstrap.bundle.min.js"></script>
<script src="${pageContext.request.contextPath}/resources/assets/js/templatemo.js"></script>
<script src="${pageContext.request.contextPath}/resources/assets/js/custom.js"></script>
<!-- End Script -->
</body>

articleEvenement/src/main/webapp/WEB-INF/views/postList.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<jsp:include page="header_${side}.jsp" />

<div class="container-fluid bg-light py-5">
<div class="row">
    <div class="col-md-6 m-auto text-center">
        <h1 class="h1">Posts</h1>
    </div>

</div>
</div>
<c:if test='${error != null && error != ""}'>
    <script>alert("${error}")</script>
</c:if>
<div class="row">
<c:forEach var="post" items="${posts}">
    <div class="col-md-4 ${post.type.name}">
        <div class="card mb-4 product-wap rounded-0">
            <div class="card rounded-0">
                <img class="card-img rounded-0 img-fluid" src="${post.image}">

                <c:if test='${side != "front"}'>

                <div class="card-img-overlay rounded-0 product-overlay d-flex align-items-center justify-content-center">
                    <ul class="list-unstyled">
                        <li><a class="btn btn-success text-white" href="${pageContext.request.contextPath}/post/${post.id}/update">Update</a></li>
                    </ul>
                </div>
                </c:if>
            </div>
            <div class="card-body">
                <ul class="w-100 list-unstyled d-flex justify-content-between mb-0">
                    <li><span class="far">by ${post.author.name}</span></li>
                </ul>
                <ul class="w-100 list-unstyled d-flex justify-content-between mb-0">
                    <li><span class="far">Creation: ${post.dateCreationToString}</span></li>
                </ul>
                <c:if test="${post.pub_date != null}">
                    <ul class="w-100 list-unstyled d-flex justify-content-between mb-0">
                        <li><span class="far">Publication: ${post.datePubToString}</span></li>
                    </ul>
                </c:if>
                <ul class="w-100 list-unstyled d-flex justify-content-between mb-0">
                    <li><a href=""><span class="far fa-heading ${post.type.name}"> ${post.titleToUpperCase}</span></a></li>
                    <li>${post.type.name}</li>
                </ul>
                <ul class="w-100 list-unstyled d-flex justify-content-between mb-0">
                    <li><span class="far fa-calendar"> ${post.date1ToString}</span></li>
                    <c:if test="${post.date2 != null && post.type.id == 2}">
                        <li><span class="far fa-calendar"> ${post.date2ToString}</span></li>
                    </c:if>
                </ul>
                <c:if test="${post.location != null}">
                <ul class="w-100 list-unstyled d-flex justify-content-between mb-0">
                    <li><span class="far fa-map-pin">${post.location}</span></li>
                </ul>
                </c:if>
<%--                <c:if test='${post.status == 0 && side == "admin" }'>--%>
<%--                    <ul class="w-100 list-unstyled d-flex justify-content-between mb-0">--%>
<%--                        <form action="${pageContext.request.contextPath}/post/${post.id}/validate" method="post">--%>
<%--                            <input type = "datetime-local" name="pubDate" class="form-control" required>--%>
<%--                            <input type="submit" value="Publier" class="btn btn-success">--%>
<%--                        </form>--%>
<%--&lt;%&ndash;                        <a href="${pageContext.request.contextPath}/post/${post.id}/validate" class="btn btn-success">Publier</a>&ndash;%&gt;--%>
<%--                    </ul>--%>
<%--                </c:if>--%>
            </div>
        </div>
    </div>
</c:forEach>
</div>
<div div="row">
    <ul class="pagination pagination-lg justify-content-center">
        <% String search = "";
            if (request.getAttribute("search") != null) { search = "&search=" + request.getAttribute("search"); } %>
        <% String status = "";
            if (request.getAttribute("status") != null) { status = "&status=" + request.getAttribute("status"); } %>
        <% if(!request.getAttribute("page").equals(1)) { %>
        <li class="page-item">
            <a class="page-link rounded-0 shadow-sm border-top-0 border-left-0 text-dark" href='<%=(request.getContextPath()+"/post/" + request.getAttribute("side")+ "?page="+(  (int)request.getAttribute("page") - 1  ) + search + status)%>'><%="<<"%></a>
        </li>
        <% } %>
        <% for(int i = 1 ; i <= (int)request.getAttribute("pageCount"); i++) { %>

        <% if(request.getAttribute("page").equals(i)) { %>
        <li class="page-item disabled">
            <a class="page-link active rounded-0 shadow-sm border-top-0 border-left-0 text-dark" href='<%=(request.getContextPath()+"/post/" + request.getAttribute("side") +"?page="+i+search + status)%>'><%=i%></a>
        </li>
        <% } else if(!request.getAttribute("page").equals(i)) { %>
        <li class="page-item">
            <a class="page-link rounded-0 shadow-sm border-top-0 border-left-0 text-dark" href='<%=(request.getContextPath()+"/post/" + request.getAttribute("side") +"?page="+i+search + status)%>'><%=i%></a>
        </li>
        <% }} %>
        <% if(!request.getAttribute("page").equals(request.getAttribute("pageCount")) && !request.getAttribute("pageCount").equals(0)) { %>
        <li class="page-item">
            <a class="page-link rounded-0 shadow-sm border-top-0 border-left-0 text-dark" href='<%=(request.getContextPath()+"/post/" + request.getAttribute("side") +"?page="+(  (int)request.getAttribute("page") + 1  ) + search + status)%>'><%=">>"%></a>
        </li>
        <% } %>
    </ul>
</div>

<jsp:include page="footer_${side}.jsp" />
</html>

articleEvenement/src/main/webapp/WEB-INF/views/rowsNumberForm.jsp
<%--
  Created by IntelliJ IDEA.
  User: andyn
  Date: 25/01/2023
  Time: 11:28
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>

<jsp:include page="header_admin.jsp" />



<div class="container-fluid bg-light py-5">
    <div class="row">
        <div class="col-md-6 m-auto text-center">
            <h1 class="h1">Update Rows Number Per Page</h1>
        </div>

    </div>
</div>


<div class="container py-5">
    <div class="row py-5">
        <form:form method="post" action="${pageContext.request.contextPath}/setting/update/rowsnumber" class="col-md-9 m-auto">

            <div class="mb-3">
                <label for="title">Value</label>
                <form:input path="valeur" type="number" class="form-control mt-1" id="title" placeholder="Value" value="${command.valeur}"/>
            </div>


            <div class="row">
                <div class="col text-end mt-2">
                    <button type="submit" class="btn btn-success btn-lg px-3">Update</button>
                </div>
            </div>
        </form:form>
        <p>${error}</p>
    </div>
</div>


<jsp:include page="footer_admin.jsp" />
</html>